### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by denguun** [FudgeRK/MyfansDownloader#10]
<img width="558" alt="2024-09-18 201731" src="https://github.com/user-attachments/assets/ed9c9ec8-e9a5-43ea-bafb-2c409d7353e1">

What should I do?
Please help me.

Thank you for making the program.

**Comment by FudgeRK** [comment]
run

`pip install requests`

**Comment by denguun** [comment]
I don't understand what you're saying.

**Comment by FudgeRK** [comment]
1.Open cmd
2.Type `pip install requests`
3.enter
4.done, run myfans code again

**Comment by denguun** [comment]
Thank you so much. ♥♥♥
