### ISSUE TITLE
Complementary dependency management features

### ISSUE THREAD

**Issue by bluems** [FudgeRK/MyfansDownloader#12]
Hello, @FudgeRK 

I'm proposing to refactor our dependency checking process by integrating `check_ffmpeg.py` into a new `helper/deps.py` file in [fork](https://github.com/bluems/MyfansDownloader/commit/7144a302264abc0821bcd3b95d1ab77f7c22b323). This change aims to improve code organization and error handling. Here's why I think this is beneficial:

* It unifies related functionality, reducing potential conflicts.
* It allows for more comprehensive error handling by running all checks together.
* It improves code clarity by housing all dependency checks in one aptly named file.

Currently, `check_ffmpeg.py` runs before `main.py`, which can lead to premature errors. Integrating it into a unified checker would resolve this issue.
I believe merging the `check_ffmpeg.py` into a more general dependency module is preferable to the reverse, as it creates a more logical and maintainable structure.
I'd appreciate your thoughts on this approach before I proceed with development and submit a PR. If you have any concerns or alternative ideas, please let me know.

**Comment by bluems** [comment]
If I may add a footnote here, the goal of this feature is to

* Ensure that the user is using python 3.8 or higher.
* The user has installed the python requirements in their environment.
* The user has added FFMPEG to their environment (consensus required).

**Comment by FudgeRK** [comment]
I checked the folk file and it's a great improvement. 
Thanks for taking the time.
Just send a request to merge. 🫡
