### ISSUE TITLE
I did what I explained, but it doesn't work.

### ISSUE THREAD

**Issue by rockkiss85** [FudgeRK/MyfansDownloader#3]
I've checked the cookies, typed them in my notepad and tried them as described, but they don't work. Is the cookies wrong by any chance?

![image](https://github.com/FudgeRK/MyfansDownloader/assets/174396287/1d3cc541-cf5f-4715-bd9a-c6e2937c1f34)

![image](https://github.com/FudgeRK/MyfansDownloader/assets/174396287/2a0b357f-1820-43bc-8987-a3aa828f76c7)

**Comment by FudgeRK** [comment]
It is impossible for cookies to be wrong.
Did you get any error?

**Comment by Hello28912048109** [comment]
I've had the same issue. I've seen the video, how do I run the same command prompt as the video in command prompt?
