### ISSUE TITLE
Videos are downloaded but images are not.

### ISSUE THREAD

**Issue by sasa9134** [FudgeRK/MyfansDownloader#4]
![제목 없음](https://github.com/user-attachments/assets/db62ecbc-2b66-439c-a9f9-7e0d809082c1)

Videos are downloaded but images are not.

**Comment by FudgeRK** [comment]
u can edit code in main.py 
same number
`elif choice == "3":
        option3()`

**Comment by sasa9134** [comment]
I selected number 3, but it does not download.

**Comment by sasa9134** [comment]
I selected number 3, but it does not download.

**Comment by FudgeRK** [comment]
download new version and try again 
https://github.com/FudgeRK/MyfansDownloader/archive/refs/heads/main.zip

**Comment by sasa9134** [comment]
When running with the new version, main.py is closed when the download starts.

**Comment by FudgeRK** [comment]
Has an error occurred?

**Comment by sasa9134** [comment]
When I run the image download, main.py exits.

**Comment by FudgeRK** [comment]
you can direct run without using main.py
`python scripts/myfans_image_dl.py`

**Comment by sasa9134** [comment]
It won't run. :(
