### ISSUE TITLE
#3 Issues are the same as issues.

### ISSUE THREAD

**Issue by Hello28912048109** [FudgeRK/MyfansDownloader#7]
The command prompt in the 1:32 video guide says D:\Myfans> on my computer, but it says D:\>Myfans> on D:\>Myfans>python main.py , and then "Myfans" is an internal or external command, an executable program, or
This is not a batch file," reveals the execution result.

**Comment by FudgeRK** [comment]
You need to download python 3 first.
https://www.python.org/downloads/

**Comment by Hello28912048109** [comment]
Thank you for your answer. I'm using Windows 11 now and Python 3.12 is installed. The program named main runs in Python.

**Comment by FudgeRK** [comment]
Glad to help. 👍

**Comment by Hello28912048109** [comment]
I'll reinstall Python 3 and ask you again if an issue arises. Thank you.

**Comment by Hello28912048109** [comment]
It's running perfectly, but it's not downloading the video. 
Do I have to subscribe to the creator I want to download the video?

The terminal has sentences as follows.

This video is 360p


This video is 360p


This video is 360p


This video is 360p


This video is 360p


This video is 360p


This video is 360p


This video is 360p


This video is 360p


This video is 360p


This video is 480p


This video is 480p


This video is 480p


This video is 480p


This video is 480p


This video is 480p


This video is 480p


This video is 480p


This video is 480p


This video is 480p

**Comment by FudgeRK** [comment]
You need to install ffmpeg and set environment variable
this link : https://phoenixnap.com/kb/ffmpeg-windows

**Comment by Hello28912048109** [comment]
Thank you so much. Now you can download the video! Is there a way to download only paid videos instead of free videos?

**Comment by FudgeRK** [comment]
You can also download paid videos if your account has a creator subscription or buy single content.
By scrap post 
`Do you want to save only free posts?` choose `no`

**Comment by Hello28912048109** [comment]
Thank you, you can shut down that issue! Thank you so much for sharing a good program for free.
